-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE ISLAMIC_FINANCE_TAKAFUL;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.ACCOUNTS (
  ACCOUNT_ID VARCHAR(20) NOT NULL, ACCOUNT_NAME VARCHAR(200), ACCOUNT_TYPE VARCHAR(30), REGION VARCHAR(50), BALANCE FLOAT, PROFIT_RATE FLOAT, STATUS VARCHAR(20), OPENED_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
  TXN_ID VARCHAR(30) NOT NULL, ACCOUNT_ID VARCHAR(20), TXN_TYPE VARCHAR(30), AMOUNT FLOAT, CURRENCY VARCHAR(5), COUNTERPARTY VARCHAR(100), TXN_DATE TIMESTAMP, STATUS VARCHAR(20), CHANNEL VARCHAR(30), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.PRODUCTS (
  PRODUCT_ID VARCHAR(20) NOT NULL, PRODUCT_NAME VARCHAR(200), CATEGORY VARCHAR(50), TENOR_MONTHS INT, PROFIT_RATE FLOAT, MIN_AMOUNT FLOAT, STATUS VARCHAR(20), LAUNCH_DATE DATE, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.CUSTOMERS (
  CUSTOMER_ID VARCHAR(20) NOT NULL, CUSTOMER_NAME VARCHAR(200), SEGMENT VARCHAR(30), REGION VARCHAR(50), REGISTRATION_DATE DATE, TOTAL_ACCOUNTS INT, LIFETIME_VALUE FLOAT, RISK_SCORE FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
