-- Generated from generator/demo_specs/aws-malaysia-islamic-finance-takaful.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-islamic-finance-takaful
-- This is the schema that is actually deployed for MY_ISLAMIC_FINANCE_TAKAFUL.

-- Alerts fire on the bottom tail of Claims Ratio
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_CLAIMS_RATIO) AS T
  FROM RAW.POLICYHOLDERS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_CLAIMS_RATIO <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_CLAIMS_RATIO), 2) AS AVG_CLAIMS_RATIO,
  ROUND(AVG(f.KPI_PERSISTENCY), 2) AS AVG_PERSISTENCY,
  ROUND(AVG(f.KPI_SOLVENCY_RATIO), 2) AS AVG_SOLVENCY_RATIO,
  ROUND(AVG(f.KPI_RESERVE_ADEQUACY), 2) AS AVG_RESERVE_ADEQUACY
FROM RAW.POLICYHOLDERS f
JOIN RAW.PROVIDER_NETWORK e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_CLAIMS_RATIO), 2) AS AVG_CLAIMS_RATIO,
  ROUND(AVG(f.KPI_PERSISTENCY), 2) AS AVG_PERSISTENCY,
  ROUND(AVG(f.KPI_SOLVENCY_RATIO), 2) AS AVG_SOLVENCY_RATIO,
  ROUND(AVG(f.KPI_RESERVE_ADEQUACY), 2) AS AVG_RESERVE_ADEQUACY
FROM RAW.POLICYHOLDERS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_CLAIMS_RATIO) AS KPI_CLAIMS_RATIO, AVG(KPI_SOLVENCY_RATIO) AS KPI_SOLVENCY_RATIO, AVG(KPI_RESERVE_ADEQUACY) AS KPI_RESERVE_ADEQUACY, AVG(KPI_PERSISTENCY) AS KPI_PERSISTENCY FROM RAW.POLICYHOLDERS),
     en AS (SELECT SUM(KPI_GROSS_CONTRIBUTIONS) AS KPI_GROSS_CONTRIBUTIONS, SUM(KPI_SURPLUS_DISTRIBUTED) AS KPI_SURPLUS_DISTRIBUTED, SUM(KPI_POLICIES_ACTIVE) AS KPI_POLICIES_ACTIVE FROM RAW.PROVIDER_NETWORK)
  SELECT 1 AS SORT_ORDER, 'Gross Contributions' AS TITLE, KPI_GROSS_CONTRIBUTIONS AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_GROSS_CONTRIBUTIONS) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Claims Ratio' AS TITLE, KPI_CLAIMS_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CLAIMS_RATIO)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Surplus Distributed' AS TITLE, KPI_SURPLUS_DISTRIBUTED AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_SURPLUS_DISTRIBUTED) / 1000000000), 1) AS DECIMAL(38,1))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Policies Active' AS TITLE, KPI_POLICIES_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_POLICIES_ACTIVE) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Solvency Ratio' AS TITLE, KPI_SOLVENCY_RATIO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SOLVENCY_RATIO)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Reserve Adequacy' AS TITLE, KPI_RESERVE_ADEQUACY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_RESERVE_ADEQUACY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Persistency' AS TITLE, KPI_PERSISTENCY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_PERSISTENCY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
