-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Takaful Claims Intelligence
-- ============================================================================
USE DATABASE ISLAMIC_TAKAFUL_CLAIMS;
USE SCHEMA ML;

-- ML.CLASSIFICATION: FRAUD_SCORING_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.CLASSIFICATION ML.FRAUD_SCORING_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FRAUD_SCORING'),
  TARGET_COLNAME => 'FRAUD_PROBABILITY'
);

-- ML.ANOMALY_DETECTION: CLAIMS_PATTERN_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.CLAIMS_PATTERN_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PROVIDER_ANALYTICS'),
  SERIES_COLNAME => 'PROVIDER_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'CLAIM_COUNT',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.CLAIMS_PATTERN_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CLAIMS_PATTERN_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PROVIDER_ANALYTICS'), SERIES_COLNAME => 'PROVIDER_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'CLAIM_COUNT'));

