-- ============================================================================
-- 99_RESET.SQL — Reset Takaful Claims Intelligence to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_TAKAFUL_CLAIMS;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_CLAIMS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD SUSPEND;
ALTER TASK IF EXISTS APP.TASK_DETECT_PATTERNS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CLAIMS_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.FRAUD_SCORING REFRESH;
ALTER DYNAMIC TABLE CURATED.PROVIDER_ANALYTICS REFRESH;
ALTER DYNAMIC TABLE CURATED.INVESTIGATION_QUEUE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_TAKAFUL_CLAIMS.RAW.CLAIMS → 15000
-- SELECT COUNT(*) FROM ISLAMIC_TAKAFUL_CLAIMS.RAW.POLICYHOLDERS → 50000
-- SELECT COUNT(*) FROM ISLAMIC_TAKAFUL_CLAIMS.RAW.CLAIM_DOCUMENTS → 8000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_DETECT_PATTERNS RESUME;
ALTER TASK IF EXISTS APP.TASK_SCORE_FRAUD RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_CLAIMS RESUME;
